scriptname SLCoiDelayedSucCurseInfectHandler extends SLCoiDelayedInfectionHandler

SLCoiInfectionSuccubusCurse property Infection auto

SLCoiInfection function GetInfection()
  return Infection
endFunction
