scriptname SLCoiDelayedLycanthropyInfectHandler extends SLCoiDelayedInfectionHandler

SLCoiInfectionLycanthropy property Infection auto

SLCoiInfection function GetInfection()
  return Infection
endFunction
